module.exports = {
   admin_puntuacion:{
       name:"admin_puntuacion",
       columns:{
            id:"id",
            user_id:"user_id",
            username:"username",
            estado:"estado"
       }
   },
   puntuacion:{
       name:"puntuacion",
       columns:{
            id:"id",
            user_id:"user_id",
            username:"username",
            first_name:"first_name",
            puntaje:"puntaje",
            grupo:"grupo"
       }
   }
}